export const smartPostAbi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "lensHubProxyContract",
        type: "address",
        internalType: "address",
      },
      {
        name: "moduleRegistryContract",
        type: "address",
        internalType: "address",
      },
      { name: "moduleOwner", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "HUB",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "LENS_HUB",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract ILensHub" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MODULE_REGISTRY",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IModuleRegistry",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "bets",
    inputs: [
      { name: "profileId", type: "uint256", internalType: "uint256" },
      { name: "pubId", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      { name: "userId", type: "uint256", internalType: "uint256" },
      { name: "judgeId", type: "uint256", internalType: "uint256" },
      { name: "currency", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "deadline", type: "uint256", internalType: "uint256" },
      { name: "active", type: "bool", internalType: "bool" },
      { name: "outcome", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "finalize",
    inputs: [
      { name: "pubId", type: "uint256", internalType: "uint256" },
      { name: "profileId", type: "uint256", internalType: "uint256" },
      { name: "outcome", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getBet",
    inputs: [
      { name: "pubId", type: "uint256", internalType: "uint256" },
      { name: "profileId", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct BetTypes.Bet",
        components: [
          { name: "userId", type: "uint256", internalType: "uint256" },
          { name: "judgeId", type: "uint256", internalType: "uint256" },
          {
            name: "currency",
            type: "address",
            internalType: "address",
          },
          { name: "amount", type: "uint256", internalType: "uint256" },
          {
            name: "deadline",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "active", type: "bool", internalType: "bool" },
          { name: "outcome", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getModuleMetadataURI",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "initializePublicationAction",
    inputs: [
      { name: "profileId", type: "uint256", internalType: "uint256" },
      { name: "pubId", type: "uint256", internalType: "uint256" },
      {
        name: "transactionExecutor",
        type: "address",
        internalType: "address",
      },
      { name: "data", type: "bytes", internalType: "bytes" },
    ],
    outputs: [{ name: "", type: "bytes", internalType: "bytes" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "metadataURI",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "processPublicationAction",
    inputs: [
      {
        name: "params",
        type: "tuple",
        internalType: "struct Types.ProcessActionParams",
        components: [
          {
            name: "publicationActedProfileId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "publicationActedId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "actorProfileId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "actorProfileOwner",
            type: "address",
            internalType: "address",
          },
          {
            name: "transactionExecutor",
            type: "address",
            internalType: "address",
          },
          {
            name: "referrerProfileIds",
            type: "uint256[]",
            internalType: "uint256[]",
          },
          {
            name: "referrerPubIds",
            type: "uint256[]",
            internalType: "uint256[]",
          },
          {
            name: "referrerPubTypes",
            type: "uint8[]",
            internalType: "enum Types.PublicationType[]",
          },
          {
            name: "actionModuleData",
            type: "bytes",
            internalType: "bytes",
          },
        ],
      },
    ],
    outputs: [{ name: "", type: "bytes", internalType: "bytes" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setModuleMetadataURI",
    inputs: [{ name: "_metadataURI", type: "string", internalType: "string" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "supportsInterface",
    inputs: [{ name: "interfaceID", type: "bytes4", internalType: "bytes4" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "BetActivated",
    inputs: [
      {
        name: "pubId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "profileId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "challengedProfileId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "BetCreated",
    inputs: [
      {
        name: "pubId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "creatorId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "userId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "judgeId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "currency",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "deadline",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "BetFinalized",
    inputs: [
      {
        name: "pubId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "profileId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "outcome",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Unstaked",
    inputs: [
      {
        name: "pubId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "profileId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "ActionAlreadyExecuted", inputs: [] },
  { type: "error", name: "BetAlreadyActive", inputs: [] },
  { type: "error", name: "BetExpired", inputs: [] },
  { type: "error", name: "BetNotActive", inputs: [] },
  { type: "error", name: "BetNotExpired", inputs: [] },
  { type: "error", name: "CurrencyNotWhitelisted", inputs: [] },
  { type: "error", name: "InvalidCaller", inputs: [] },
  { type: "error", name: "InvalidDeadline", inputs: [] },
  { type: "error", name: "InvalidJudge", inputs: [] },
  { type: "error", name: "InvalidOutcome", inputs: [] },
  { type: "error", name: "InvalidVote", inputs: [] },
  { type: "error", name: "NotHub", inputs: [] },
  { type: "error", name: "NotStaked", inputs: [] },
];
